ifeq ($(BLUETOOTH_USE_BPLUS),true)
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SRC_FILES:=  bplus_customize.c

ifneq ($(BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR),)
      LOCAL_C_INCLUDES += $(BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR)
      LOCAL_CFLAGS += -DHAS_BDROID_BUILDCFG
endif

LOCAL_C_INCLUDES+= . \

LOCAL_SHARED_LIBRARIES := libcutils
LOCAL_MODULE := libbt_cust
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES

include $(BUILD_SHARED_LIBRARY)
endif
